Sub Macro1()

  With Selection.Font

    .Name = "Times New Roman"

    .Size = 10

    .Bold = False

    .Italic = False

    .Underline = wdUnderlineNone

    .UnderlineColor = wdColorAutomatic

    .StrikeThrough = False

    .DoubleStrikeThrough = False

    .Outline = False

    .Emboss = False

    .Shadow = False

    .Hidden = False

    .SmallCaps = False

    .AllCaps = False

    .Color = wdColorAutomatic

    .Engrave = False

    .Superscript = False

    .Subscript = False

    .Spacing = 0

    .Scaling = 100

    .Position = 0

    .Kerning = 0

    .Animation = wdAnimationNone

  End With

End Sub